<project default="all" xmlns:if="ant:if">
        <target name="all" depends="buildiso">
        </target>

		<target name="print-vars">
			<echo message="BASE_ISO_FILE: ${BASE_ISO_FILE}"/>
			<echo message="DEB_DIRS: ${DEB_DIRS}"/>
		</target>

        <target name="buildiso" depends="print-vars">
                <exec executable="bash" >
			<arg value="./create-iso.sh" />

			<arg value="-i" if:set="BASE_ISO_FILE"/>
			<arg value="${BASE_ISO_FILE}" if:set="BASE_ISO_FILE"/>

			<arg value="-p" if:set="DEB_DIRS"/>
			<arg value="${DEB_DIRS}" if:set="DEB_DIRS"/>
		</exec>
        </target>
</project>
